name: Caching Primes

on: push

jobs:
  build:
    runs-on: ${{matrix.os}}
    
    strategy:
      fail-fast: false
      matrix:
        node: [16]
        os: [macOS-11, macOS-latest]
    
    steps:
    - uses: actions/checkout@v1

    - name: set python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11" 

    - name: shell
      run: bash upload.sh
